archives:
  -
    # No .Os map in checksum.name_template, so hardcoding here as well.
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}"

builds:
  # You can have multiple builds defined as a yaml list.
  -
    id: "windows"
    goos:
      - windows
    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64
    ldflags:
      - -X github.com/alphasoc/nfr/version.Version={{ .Version }}


checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums_windows.txt"

release:
  # Disable the actual release.  Done elsewhere.
  disable: true

# Sign all artifacts.
signs:
  - artifacts: all
